language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install -e .
    - pip install coverage coveralls mock flake8

before_script:
    flake8 rcontrol tests setup.py

script:
    - coverage run setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi
